### ISSUE TITLE
Homebrew warns "`bottle :unneeded` is deprecated"

### ISSUE THREAD

**Issue by aramprice** [aquasecurity/homebrew-trivy#2]
> Warning: Calling bottle :unneeded is deprecated! There is no replacement.
> Please report this issue to the aquasecurity/trivy tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/aquasecurity/homebrew-trivy/trivy.rb:9

https://github.com/aquasecurity/homebrew-trivy/blob/ef953a6ec4373e895ed5ec28b2bbb1233a3f0892/trivy.rb#L9

**Comment by psibre** [comment]
Since the formula is auto-generated and the underlying issue was solved in goreleaser/goreleaser#2591, this will solve itself once GoReleaser is upgrade to [v0.183.0](https://github.com/goreleaser/goreleaser/releases/tag/v0.183.0) or later.

**Comment by aramprice** [comment]
Thanks for the update, feel free to close this in the mean time.

**Comment by knqyf263** [comment]
Thanks for the report! We released v0.20.2 and it addressed this issue hopefully.
